//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TestTD.ServicioBilletera {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="https://www.redefectiva.net/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistraCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaSaldoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaMovimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AbonoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetiroOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::TestTD.Properties.Settings.Default.TestTD_ServicioBilletera_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event RegistraCuentaCompletedEventHandler RegistraCuentaCompleted;
        
        /// <remarks/>
        public event ConsultaSaldoCompletedEventHandler ConsultaSaldoCompleted;
        
        /// <remarks/>
        public event ConsultaMovimientoCompletedEventHandler ConsultaMovimientoCompleted;
        
        /// <remarks/>
        public event AbonoCompletedEventHandler AbonoCompleted;
        
        /// <remarks/>
        public event CargoCompletedEventHandler CargoCompleted;
        
        /// <remarks/>
        public event RetiroCompletedEventHandler RetiroCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.redefectiva.net/HelloWorld", RequestNamespace="https://www.redefectiva.net/", ResponseNamespace="https://www.redefectiva.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.redefectiva.net/RegistraCuenta", RequestNamespace="https://www.redefectiva.net/", ResponseNamespace="https://www.redefectiva.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegistraCuenta(int ClientId, int Timestamp, string Token, string Telefono, string Correo, string RFC, string PIN, string Descripcion, string RazonSocial) {
            object[] results = this.Invoke("RegistraCuenta", new object[] {
                        ClientId,
                        Timestamp,
                        Token,
                        Telefono,
                        Correo,
                        RFC,
                        PIN,
                        Descripcion,
                        RazonSocial});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegistraCuentaAsync(int ClientId, int Timestamp, string Token, string Telefono, string Correo, string RFC, string PIN, string Descripcion, string RazonSocial) {
            this.RegistraCuentaAsync(ClientId, Timestamp, Token, Telefono, Correo, RFC, PIN, Descripcion, RazonSocial, null);
        }
        
        /// <remarks/>
        public void RegistraCuentaAsync(int ClientId, int Timestamp, string Token, string Telefono, string Correo, string RFC, string PIN, string Descripcion, string RazonSocial, object userState) {
            if ((this.RegistraCuentaOperationCompleted == null)) {
                this.RegistraCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistraCuentaOperationCompleted);
            }
            this.InvokeAsync("RegistraCuenta", new object[] {
                        ClientId,
                        Timestamp,
                        Token,
                        Telefono,
                        Correo,
                        RFC,
                        PIN,
                        Descripcion,
                        RazonSocial}, this.RegistraCuentaOperationCompleted, userState);
        }
        
        private void OnRegistraCuentaOperationCompleted(object arg) {
            if ((this.RegistraCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistraCuentaCompleted(this, new RegistraCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.redefectiva.net/ConsultaSaldo", RequestNamespace="https://www.redefectiva.net/", ResponseNamespace="https://www.redefectiva.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaSaldo(int ClientId, int Timestamp, string Token, int NumCuenta) {
            object[] results = this.Invoke("ConsultaSaldo", new object[] {
                        ClientId,
                        Timestamp,
                        Token,
                        NumCuenta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaSaldoAsync(int ClientId, int Timestamp, string Token, int NumCuenta) {
            this.ConsultaSaldoAsync(ClientId, Timestamp, Token, NumCuenta, null);
        }
        
        /// <remarks/>
        public void ConsultaSaldoAsync(int ClientId, int Timestamp, string Token, int NumCuenta, object userState) {
            if ((this.ConsultaSaldoOperationCompleted == null)) {
                this.ConsultaSaldoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaSaldoOperationCompleted);
            }
            this.InvokeAsync("ConsultaSaldo", new object[] {
                        ClientId,
                        Timestamp,
                        Token,
                        NumCuenta}, this.ConsultaSaldoOperationCompleted, userState);
        }
        
        private void OnConsultaSaldoOperationCompleted(object arg) {
            if ((this.ConsultaSaldoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaSaldoCompleted(this, new ConsultaSaldoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.redefectiva.net/ConsultaMovimiento", RequestNamespace="https://www.redefectiva.net/", ResponseNamespace="https://www.redefectiva.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaMovimiento(int ClientId, int Timestamp, string Token, int NumCuenta, int Periodo) {
            object[] results = this.Invoke("ConsultaMovimiento", new object[] {
                        ClientId,
                        Timestamp,
                        Token,
                        NumCuenta,
                        Periodo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaMovimientoAsync(int ClientId, int Timestamp, string Token, int NumCuenta, int Periodo) {
            this.ConsultaMovimientoAsync(ClientId, Timestamp, Token, NumCuenta, Periodo, null);
        }
        
        /// <remarks/>
        public void ConsultaMovimientoAsync(int ClientId, int Timestamp, string Token, int NumCuenta, int Periodo, object userState) {
            if ((this.ConsultaMovimientoOperationCompleted == null)) {
                this.ConsultaMovimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaMovimientoOperationCompleted);
            }
            this.InvokeAsync("ConsultaMovimiento", new object[] {
                        ClientId,
                        Timestamp,
                        Token,
                        NumCuenta,
                        Periodo}, this.ConsultaMovimientoOperationCompleted, userState);
        }
        
        private void OnConsultaMovimientoOperationCompleted(object arg) {
            if ((this.ConsultaMovimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaMovimientoCompleted(this, new ConsultaMovimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.redefectiva.net/Abono", RequestNamespace="https://www.redefectiva.net/", ResponseNamespace="https://www.redefectiva.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Abono(int ClientId, int Timestamp, string Token, int NumCuenta, int TipoRecurso, string Referencia, string Descripcion, decimal Monto) {
            object[] results = this.Invoke("Abono", new object[] {
                        ClientId,
                        Timestamp,
                        Token,
                        NumCuenta,
                        TipoRecurso,
                        Referencia,
                        Descripcion,
                        Monto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AbonoAsync(int ClientId, int Timestamp, string Token, int NumCuenta, int TipoRecurso, string Referencia, string Descripcion, decimal Monto) {
            this.AbonoAsync(ClientId, Timestamp, Token, NumCuenta, TipoRecurso, Referencia, Descripcion, Monto, null);
        }
        
        /// <remarks/>
        public void AbonoAsync(int ClientId, int Timestamp, string Token, int NumCuenta, int TipoRecurso, string Referencia, string Descripcion, decimal Monto, object userState) {
            if ((this.AbonoOperationCompleted == null)) {
                this.AbonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAbonoOperationCompleted);
            }
            this.InvokeAsync("Abono", new object[] {
                        ClientId,
                        Timestamp,
                        Token,
                        NumCuenta,
                        TipoRecurso,
                        Referencia,
                        Descripcion,
                        Monto}, this.AbonoOperationCompleted, userState);
        }
        
        private void OnAbonoOperationCompleted(object arg) {
            if ((this.AbonoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AbonoCompleted(this, new AbonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.redefectiva.net/Cargo", RequestNamespace="https://www.redefectiva.net/", ResponseNamespace="https://www.redefectiva.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Cargo(int ClientId, int Timestamp, string Token, int NumCuenta, int TipoRecurso, string Referencia, string Descripcion, decimal Monto) {
            object[] results = this.Invoke("Cargo", new object[] {
                        ClientId,
                        Timestamp,
                        Token,
                        NumCuenta,
                        TipoRecurso,
                        Referencia,
                        Descripcion,
                        Monto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CargoAsync(int ClientId, int Timestamp, string Token, int NumCuenta, int TipoRecurso, string Referencia, string Descripcion, decimal Monto) {
            this.CargoAsync(ClientId, Timestamp, Token, NumCuenta, TipoRecurso, Referencia, Descripcion, Monto, null);
        }
        
        /// <remarks/>
        public void CargoAsync(int ClientId, int Timestamp, string Token, int NumCuenta, int TipoRecurso, string Referencia, string Descripcion, decimal Monto, object userState) {
            if ((this.CargoOperationCompleted == null)) {
                this.CargoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargoOperationCompleted);
            }
            this.InvokeAsync("Cargo", new object[] {
                        ClientId,
                        Timestamp,
                        Token,
                        NumCuenta,
                        TipoRecurso,
                        Referencia,
                        Descripcion,
                        Monto}, this.CargoOperationCompleted, userState);
        }
        
        private void OnCargoOperationCompleted(object arg) {
            if ((this.CargoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargoCompleted(this, new CargoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.redefectiva.net/Retiro", RequestNamespace="https://www.redefectiva.net/", ResponseNamespace="https://www.redefectiva.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Retiro(int ClientId, int Timestamp, string Token, int NumCuenta, int Banco, string CLABE, string RefNum, string RefAlfa, string Descripcion, decimal Monto) {
            object[] results = this.Invoke("Retiro", new object[] {
                        ClientId,
                        Timestamp,
                        Token,
                        NumCuenta,
                        Banco,
                        CLABE,
                        RefNum,
                        RefAlfa,
                        Descripcion,
                        Monto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RetiroAsync(int ClientId, int Timestamp, string Token, int NumCuenta, int Banco, string CLABE, string RefNum, string RefAlfa, string Descripcion, decimal Monto) {
            this.RetiroAsync(ClientId, Timestamp, Token, NumCuenta, Banco, CLABE, RefNum, RefAlfa, Descripcion, Monto, null);
        }
        
        /// <remarks/>
        public void RetiroAsync(int ClientId, int Timestamp, string Token, int NumCuenta, int Banco, string CLABE, string RefNum, string RefAlfa, string Descripcion, decimal Monto, object userState) {
            if ((this.RetiroOperationCompleted == null)) {
                this.RetiroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetiroOperationCompleted);
            }
            this.InvokeAsync("Retiro", new object[] {
                        ClientId,
                        Timestamp,
                        Token,
                        NumCuenta,
                        Banco,
                        CLABE,
                        RefNum,
                        RefAlfa,
                        Descripcion,
                        Monto}, this.RetiroOperationCompleted, userState);
        }
        
        private void OnRetiroOperationCompleted(object arg) {
            if ((this.RetiroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetiroCompleted(this, new RetiroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RegistraCuentaCompletedEventHandler(object sender, RegistraCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistraCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistraCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultaSaldoCompletedEventHandler(object sender, ConsultaSaldoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaSaldoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaSaldoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultaMovimientoCompletedEventHandler(object sender, ConsultaMovimientoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaMovimientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaMovimientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AbonoCompletedEventHandler(object sender, AbonoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AbonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AbonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CargoCompletedEventHandler(object sender, CargoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RetiroCompletedEventHandler(object sender, RetiroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetiroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetiroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591